### ISSUE TITLE
Import/backup Instagram account

### ISSUE THREAD

**Issue by vinzv** [hannesmannerheim/quitim#1]
An awesome (not to say "killer") feature would be a way to import photos posted on Instagram including metadata like date and time. Maybe https://github.com/aaronpk/OwnYourGram has some useful code for that?

Just thinking:
A possible hack would be grabbing a backup via http://instaport.me which generates a zip file with images name after this scheme "2014-03-08_1394320871.jpg". So if it's possible with gnusocial to date posts back in time there could be a way to post at least the old pictures plus date via curl.

**Comment by hannesmannerheim** [comment]
on a second thought, i think this should be designed as a stand alone gnu social plugin. would be useful for any gnu social user. closing this because i don't plan on implementing it in this plugin. but thanks!
