### ISSUE TITLE
thumbnails size

### ISSUE THREAD

**Issue by mama21mama** [hannesmannerheim/quitim#2]
El problema es la ausencia de thumbnails.

Existe el thumbnails pero no trabaja como es debido.

Todas las fotos 55.3MB > https://quit.im/hannes

Mi thumbnails 800k http://cut7.tk/b7f

**Comment by hannesmannerheim** [comment]
it's working like intended. i'm considering making the thumbnails even bigger.

**Comment by mama21mama** [comment]
I feel good for you. not talking about the visual size. Weight speak file size.

**Comment by hannesmannerheim** [comment]
everything on the page https://quit.im/hannes is 2.5MB

![skarmavbild 2015-06-22 kl 18 49 00](https://cloud.githubusercontent.com/assets/2437812/8287344/7694b9f4-190f-11e5-94b7-b9e458ff85b9.png)

**Comment by hannesmannerheim** [comment]
but of course _all_ images i ever posted adds upp to a lot of megabytes. but each thumbnail is 800x600 and 100-200 kB. nothing wrong with that.

**Comment by mama21mama** [comment]
well ... not that my browser cache load so much stuff.
